import { useNavigate } from 'react-router-dom'

const medicalTexture = 'https://www.figma.com/api/mcp/asset/5a5ce48b-c78a-4fe0-9803-35e297f3b7fc.png'
const iconClock = 'https://www.figma.com/api/mcp/asset/6c094ddb-a80d-498c-acf6-c6a62b1532fe.svg'
const iconRoute = 'https://www.figma.com/api/mcp/asset/6f8d8823-f545-42a7-9415-9d5665f242d2.svg'
const iconFollow = 'https://www.figma.com/api/mcp/asset/1a630e9b-a205-4914-bf2b-158b807e04ff.svg'
const iconMargin = 'https://www.figma.com/api/mcp/asset/7093081a-31bc-461c-8670-7ffaf72ed467.svg'
const flowLines = 'https://www.figma.com/api/mcp/asset/9d636ab5-87dc-43b7-95a8-1f13b14bc471.svg'
const iconPatient = 'https://www.figma.com/api/mcp/asset/07094935-0e8e-4a21-bdd6-c2b6fc236116.svg'
const iconFacility = 'https://www.figma.com/api/mcp/asset/1869893f-8bf2-41b5-8f86-b2bb652da3bb.svg'
const iconLanguage = 'https://www.figma.com/api/mcp/asset/193fde63-9d95-41d7-9aac-d17ae012e5da.svg'
const iconVoice = 'https://www.figma.com/api/mcp/asset/fffcf86a-dfcb-479a-9b8f-d680981cdfe1.svg'
const iconConnect = 'https://www.figma.com/api/mcp/asset/2029062e-af26-44cd-9124-75a560e91d00.svg'

// Primary CTA button — green bg, white text
function CtaButton({ children, className = '', onClick }) {
	const navigate = useNavigate()
	return (
		<button
			onClick={onClick || (() => navigate('/signup'))}
			className={`inline-flex items-center justify-center rounded-full px-8 py-4 text-sm font-semibold tracking-[.01em] text-white transition-transform hover:-translate-y-0.5 primary-cta bg-[#29574b] shadow-[0_10px_40px_-10px_rgba(41,87,75,.08)] ${className}`}
		>
			{children}
		</button>
	)
}

// Secondary / anchor button
function SecondaryButton({ children, href = '#features', className = '' }) {
	return (
		<a
			href={href}
			className={`inline-flex items-center justify-center rounded-full px-8 py-4 text-sm font-semibold tracking-[.01em] transition-transform hover:-translate-y-0.5 border border-[#c0c8c4]/30 bg-[#e9efec] text-[#29574b] ${className}`}
		>
			{children}
		</a>
	)
}

function Navbar() {
	const navigate = useNavigate()
	return <nav className="fixed inset-x-0 top-0 z-50 border-b border-[#29574b]/10 bg-transparent px-5 py-3 sm:px-8 lg:px-16">
		<div className="mx-auto flex max-w-[1152px] items-center justify-between">
			<a href="#top" className="brand font-serif text-2xl font-semibold sm:text-[32px]">MediMate</a>
			<div className="hidden items-center gap-8 text-sm font-semibold text-[#404845] md:flex">
				<a className="border-b-2 border-[#29574b] pb-1 text-[#29574b]" href="#features">Features</a><a href="#journey">How it works</a><a href="#patients">For Patients</a><a href="#facilities">For Facilities</a><a href="#faq">FAQ</a>
			</div>
			<div className="flex items-center gap-4 text-sm font-semibold">
				<button onClick={() => navigate('/login')} className="hidden sm:block text-[#29574b] hover:underline">Login</button>
				<CtaButton onClick={() => navigate('/signup')} className="px-5 py-2.5">Sign up</CtaButton>
			</div>
		</div>
	</nav>
}

function Hero() {
	return <section id="top" className="relative overflow-hidden px-5 pb-20 pt-32 sm:px-8 lg:px-16 lg:pt-40">
		<div className="relative mx-auto grid max-w-[1152px] items-center gap-12 lg:grid-cols-[5fr_7fr]">
			<div className="order-2 lg:order-1"><h1 className="max-w-xl font-serif text-5xl font-bold leading-[1.1] tracking-[-.02em] text-[#29574b] sm:text-6xl">Better care,<br />closer to home.</h1><p className="mt-6 max-w-md text-lg leading-relaxed text-[#404845]">Navigate your health journey with clarity. MediMate connects you to the right care, at the right time, with quiet confidence.</p><div className="mt-8 flex flex-wrap gap-4"><CtaButton>Start your journey</CtaButton><SecondaryButton href="#journey">See how it works</SecondaryButton></div></div>
			<div className="relative order-1 h-[420px] sm:h-[520px] lg:order-2 lg:h-[600px]"><div className="absolute inset-0 overflow-hidden rounded-[40px] border border-[#c0c8c4]/20 bg-[#c3e9f0]/20 shadow-[0_10px_40px_-10px_rgba(41,87,75,.08)]"><img src={medicalTexture} alt="Abstract medical data visualization" className="h-full w-full object-cover opacity-80 mix-blend-multiply" /></div><MiniReferral /><RiskCard /></div>
		</div>
	</section>
}

function MiniReferral() { return <div className="absolute right-5 top-5 w-56 rounded-[28px] border border-[#c0c8c4]/30 bg-[#f5fbf7] p-5 shadow-[0_10px_40px_-10px_rgba(41,87,75,.08)] sm:right-10 sm:w-72"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-full bg-[#426f63]/20"><img src={iconRoute} alt="" className="size-5" /></div><div><strong className="block text-sm">CHC Manesar</strong><span className="text-xs font-bold text-[#404845]">Recommended Match</span></div></div><div className="mt-4 flex justify-between rounded-2xl bg-[#eff5f1] px-3 py-3 text-xs font-bold text-[#404845]"><span>Wait Time</span><b className="text-[#29574b]">~15 mins</b></div></div> }
function RiskCard() { return <div className="absolute bottom-10 left-5 w-52 rounded-[28px] border border-[#c0c8c4]/30 bg-[#f5fbf7] p-6 shadow-[0_10px_40px_-10px_rgba(41,87,75,.08)] sm:left-10 sm:w-64"><p className="text-[10px] font-bold tracking-[.12em] text-[#404845]">HEALTH ASSESSMENT</p><div className="mt-2 flex items-end gap-2"><strong className="font-serif text-5xl text-[#29574b]">85</strong><span className="mb-2 text-sm text-[#404845]">/100</span></div><div className="mt-3 h-2 rounded-full bg-[#dee4e0]"><div className="h-full w-[85%] rounded-full bg-[#29574b]" /></div></div> }

function Problem() { const items = [['Is this serious?', "Symptoms are confusing. Knowing when to act shouldn't be a guessing game.", iconClock], ['Where should I go?', 'Navigating clinics, wait times, and specialties adds stress to sickness.', iconRoute], ["What's next?", 'The journey rarely ends after one visit. Follow-ups get lost in the noise.', iconFollow]]; return <section className="bg-[#eff5f1]/50 px-5 py-20 sm:px-8 lg:px-16"><div className="mx-auto max-w-[1152px]"><SectionTitle>Finding care is only part of the<br className="hidden sm:block" /> problem.</SectionTitle><div className="mt-12 grid gap-10 md:grid-cols-3 md:gap-16">{items.map(([title, text, icon], index) => <article key={title} className={`max-w-xs ${index === 1 ? 'md:mt-16' : index === 2 ? 'md:mt-32' : ''}`}><img src={icon} alt="" className="mb-6 size-7 opacity-50" /><h3 className="font-serif text-3xl font-semibold text-[#171d1b]">{title}</h3><p className="mt-2 leading-relaxed text-[#404845]">{text}</p></article>)}</div></div></section> }
function SectionTitle({ children }) { return <h2 className="text-center font-serif text-4xl font-semibold leading-tight text-[#29574b] sm:text-5xl">{children}</h2> }

function ChatPreview() { return <div className="relative flex h-[500px] flex-col rounded-[48px] border border-[#c0c8c4]/30 bg-[#f5fbf7] p-[25px] shadow-[0_10px_40px_-10px_rgba(41,87,75,.08)] lg:col-span-5"><div className="min-h-0 flex-1 overflow-hidden pb-4"><div className="flex flex-col gap-4"><p className="w-fit max-w-full rounded-2xl rounded-tl-sm bg-[#eff5f1] px-4 py-[15px] text-base leading-[25.6px]">Hi there. How are you feeling today?</p><p className="ml-auto w-fit max-w-[90%] rounded-2xl rounded-tr-sm bg-[#29574b] px-4 py-[14.8px] pr-8 text-base leading-[25.6px] text-white">I've had a really bad headache for two days.</p><p className="w-fit max-w-[95%] rounded-2xl rounded-tl-sm bg-[#eff5f1] px-4 py-[14.8px] pr-12 text-base leading-[25.6px]">I understand. Is the pain sharp or throbbing? Any sensitivity to light?</p></div></div><div className="flex items-center justify-between rounded-[32px] border border-[#ba1a1a]/20 bg-[#ffdad6]/30 p-[17px]"><div><p className="text-xs font-bold uppercase leading-[14.4px] text-[#93000a]">Assessment complete</p><strong className="mt-1 block text-sm font-semibold leading-[19.6px] tracking-[.01em]">Moderate Risk Detected</strong></div><button className="rounded-full border border-[#c0c8c4]/30 bg-[#f5fbf7] px-[17px] py-2 text-xs font-bold leading-[14.4px] text-[#29574b]">Find Care</button></div></div> }
function Assistant() { return <section id="features" className="px-5 py-20 sm:px-8 lg:px-16"><div className="mx-auto grid max-w-[1152px] items-center gap-8 lg:grid-cols-12"><ChatPreview /><div className="lg:col-start-7 lg:col-span-6"><h2 className="font-serif text-4xl font-semibold leading-[1.2] text-[#29574b] sm:text-5xl">Clarity from the first<br />symptom.</h2><p className="mt-6 text-lg leading-[1.6] text-[#404845]">Our AI Health Assistant engages in a natural conversation to understand your condition, providing an immediate, empathetic assessment.</p><ul className="mt-8 space-y-4 text-base text-[#171d1b]"><li className="flex items-center gap-4"><img src={iconMargin} alt="" className="size-5" />Conversational symptom checking</li><li className="flex items-center gap-4"><img src={iconMargin} alt="" className="size-5" />Instant risk stratification</li></ul></div></div></section> }

function Referral() { const chips = ['Risk', 'Distance', 'Doctor', 'Queue', 'Diagnostics']; return <section className="bg-[#eff5f1]/50 px-5 py-20 sm:px-8 lg:px-16"><div className="mx-auto grid max-w-[1152px] items-center gap-12 lg:grid-cols-5"><div className="lg:col-span-2"><h2 className="font-serif text-4xl font-semibold leading-tight text-[#29574b] sm:text-5xl">Not just nearby.<br />Right for you.</h2><p className="mt-6 text-lg leading-relaxed text-[#404845]">Intelligent matching connects you with facilities based on your specific risk profile, real-time availability, distance, and required diagnostics.</p><div className="mt-7 flex flex-wrap gap-3">{chips.map((chip) => <span key={chip} className="rounded-full border border-[#c0c8c4]/30 bg-[#f5fbf7] px-4 py-2 text-xs font-bold">{chip}</span>)}</div></div><div className="rounded-[40px] border border-[#c0c8c4]/30 bg-[#f5fbf7] p-8 shadow-[0_10px_40px_-10px_rgba(41,87,75,.08)] lg:col-span-3"><div className="flex items-center justify-between"><div className="flex items-center gap-4"><div className="grid size-12 place-items-center rounded-full bg-[#426f63]/20"><img src={iconRoute} alt="" className="size-5" /></div><div><h3 className="font-serif text-2xl">CHC Manesar</h3><p className="text-sm text-[#404845]">Recommended Facility</p></div></div><span className="rounded-full bg-[#29574b]/10 px-3 py-1 text-xs font-bold text-[#29574b]">Top Match</span></div><div className="mt-7 grid grid-cols-2 gap-4">{[['DISTANCE', '5.2 km'], ['WAIT TIME', '~25 mins'], ['AVAILABLE', 'Doctor & CBC'], ['QUEUE', '4 Patients']].map(([label, value]) => <div key={label} className="rounded-3xl bg-[#eff5f1] p-4"><p className="text-[10px] font-bold text-[#404845]">{label}</p><strong className="mt-1 block text-lg">{value}</strong></div>)}</div><button className="mt-6 w-full rounded-3xl bg-[#29574b] py-4 text-sm font-semibold text-white">Confirm Referral</button></div></div></section> }

function Journey() { const steps = [['1', 'Screening', 'AI symptom assessment'], ['2', 'Referral', 'Smart facility matching'], ['3', 'Appointment', 'In progress'], ['4', 'Consultation', 'Doctor evaluation'], ['5', 'Diagnostics', 'Lab tests if needed'], ['6', 'Treatment', 'Care plan execution'], ['7', 'Follow-up', 'Continued care']]; return <section id="journey" className="px-5 py-20 sm:px-8 lg:px-16"><div className="mx-auto max-w-[1152px]"><SectionTitle>A referral isn't the finish line.</SectionTitle><div className="mt-16 overflow-x-auto pb-8"><div className="relative flex min-w-[840px] justify-between gap-4 px-4"><div className="absolute left-8 right-8 top-4 h-0.5 bg-[#dee4e0]" /><div className="absolute left-8 top-4 h-0.5 w-[32%] bg-[#29574b]" />{steps.map(([number, title, detail], index) => <div key={title} className="relative z-10 w-28 text-center"><div className={`mx-auto grid size-8 place-items-center rounded-full text-sm font-bold ${index < 2 ? 'bg-[#29574b] text-white' : index === 2 ? 'bg-[#426f63] text-[#bff0e1] ring-4 ring-[#426f63]/20' : 'bg-[#dee4e0] text-[#404845]'}`}>{number}</div><h3 className={`mt-4 text-sm font-semibold ${index === 2 ? 'text-[#29574b]' : ''}`}>{title}</h3><p className="mt-2 text-xs font-bold leading-tight text-[#404845]">{detail}</p></div>)}</div></div></div></section> }

const stats = [['12', 'DOCTORS'], ['8', 'AVAILABLE'], ['24', 'WAITING'], ['67', 'TREATED'], ['4', 'HIGH RISK']];
function Dashboard() { return <section id="facilities" className="bg-[#e9efec] px-5 py-20 sm:px-8 lg:px-16"><div className="mx-auto max-w-[1152px]"><SectionTitle>Better visibility for healthcare teams.</SectionTitle><div className="mt-12 overflow-hidden rounded-2xl border border-[#c0c8c4]/30 bg-[#f5fbf7] p-5 shadow-[0_10px_40px_-10px_rgba(41,87,75,.08)] sm:p-8"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-[#c0c8c4]/30 pb-5"><h3 className="font-serif text-2xl sm:text-3xl">Facility Dashboard</h3><span className="rounded-full bg-[#426f63]/20 px-4 py-2 text-sm font-semibold text-[#29574b]">CHC Manesar Command Center</span></div><div className="grid grid-cols-2 gap-3 py-5 sm:grid-cols-5 sm:gap-4">{stats.map(([number, label], index) => <div key={label} className={`rounded-full bg-[#eff5f1] p-4 text-center ${index === 4 ? 'border border-[#ba1a1a]/20 bg-[#ffdad6]/50' : ''}`}><strong className={`block font-serif text-3xl ${index === 4 ? 'text-[#ba1a1a]' : 'text-[#29574b]'}`}>{number}</strong><span className={`text-[10px] font-bold ${index === 4 ? 'text-[#93000a]' : 'text-[#404845]'}`}>{label}</span></div>)}</div><p className="border-b border-[#c0c8c4]/30 pb-3 text-xs font-bold tracking-[.08em] text-[#404845]">HIGH-RISK INCOMING PATIENTS</p><div className="min-w-[660px] text-sm"><div className="grid grid-cols-[1.3fr_1fr_1fr_3fr] border-b border-[#c0c8c4]/30 py-3 font-bold text-[#404845]"><span>Patient</span><span>ETA</span><span>Risk Level</span><span>Suggested Action</span></div>{[['Ramesh K.', '10 mins', 'High', 'Prepare ECG & Cardiology Consult'], ['Sunita M.', '15 mins', 'High', 'Oxygen Support Ready'], ['Amit P.', '25 mins', 'High', 'Surgical Team Standby']].map((row) => <div key={row[0]} className="grid grid-cols-[1.3fr_1fr_1fr_3fr] border-b border-[#c0c8c4]/10 py-4"><strong>{row[0]}</strong><span className="text-[#404845]">{row[1]}</span><span className="w-fit rounded-full bg-[#ba1a1a]/10 px-3 py-1 text-xs font-bold text-[#ba1a1a]">{row[2]}</span><span>{row[3]}</span></div>)}</div></div></div></section> }

function Connected() { return <section className="px-5 py-20 sm:px-8 lg:px-16"><div className="mx-auto max-w-[1152px]"><SectionTitle>One platform. A connected healthcare journey.</SectionTitle><div className="relative mx-auto mt-12 flex max-w-3xl items-center justify-between"><img src={flowLines} alt="" className="absolute inset-x-0 top-1/2 hidden h-40 w-full -translate-y-1/2 md:block" /><div className="relative grid h-40 w-32 place-items-center rounded-[40px] border border-[#c0c8c4]/30 bg-[#f5fbf7] p-4 text-center shadow-sm"><img src={iconPatient} alt="" className="size-5" /><strong className="text-sm">Patient</strong><span className="text-xs font-bold text-[#404845]">Symptoms</span></div><div className="relative flex flex-col gap-28 text-center text-sm font-semibold text-[#29574b]"><span className="rounded-2xl bg-[#eff5f1] px-4 py-2">AI &amp; Risk</span><span className="rounded-2xl bg-[#eff5f1] px-4 py-2">Referral</span></div><div className="relative grid h-40 w-32 place-items-center rounded-[40px] border border-[#c0c8c4]/30 bg-[#f5fbf7] p-4 text-center shadow-sm"><img src={iconFacility} alt="" className="size-6" /><strong className="text-sm">Facility</strong><span className="text-xs font-bold text-[#404845]">Doctor, Treatment</span></div></div></div></section> }

function Accessibility() { const cards = [['Language', 'Native support for Hindi, Marathi, and regional languages to ensure everyone is understood.', iconLanguage], ['Voice', 'Integrated Speech-to-Text allows natural conversation without needing to type complex medical terms.', iconVoice], ['Connectivity', 'Built as a Progressive Web App (PWA) optimized for low-connectivity environments.', iconConnect]]; return <section id="patients" className="bg-[#eff5f1]/50 px-5 py-20 sm:px-8 lg:px-16"><div className="mx-auto max-w-[1152px]"><SectionTitle>Designed for the real world.</SectionTitle><div className="mt-12 grid gap-8 md:grid-cols-3">{cards.map(([title, text, icon]) => <article key={title} className="rounded-2xl border border-[#c0c8c4]/30 bg-[#f5fbf7] p-8 text-center shadow-[0_10px_40px_-10px_rgba(41,87,75,.08)]"><img src={icon} alt="" className="mx-auto h-8 max-w-9" /><h3 className="mt-5 font-serif text-3xl font-semibold">{title}</h3><p className="mt-4 leading-relaxed text-[#404845]">{text}</p></article>)}</div></div></section> }

function Footer() { return <><section id="start" className="bg-[#ece1d6] px-5 py-20 text-center sm:px-8"><h2 className="font-serif text-5xl font-bold leading-tight text-[#201b14] sm:text-6xl">Better care starts with the<br />next step.</h2><CtaButton className="mt-8 px-10 py-5 text-lg">Join MediMate Today</CtaButton></section><footer id="faq" className="bg-[#1e342e] px-5 py-16 text-[#ece1d6] sm:px-8 lg:px-16"><div className="mx-auto max-w-[1152px]"><div className="grid gap-12 border-b border-[#ece1d6]/20 pb-12 md:grid-cols-[2.5fr_1fr_1fr_1fr_1fr]"><div><h2 className="font-serif text-4xl font-bold">MediMate</h2><p className="mt-3 text-lg opacity-80">Connected care, closer to home.</p></div>{[['PLATFORM', 'Features', 'How it works', 'Pricing'], ['FOR PATIENTS', 'Find Care', 'Symptom Checker', 'Patient Portal'], ['FOR FACILITIES', 'Partner with us', 'Dashboard Login', 'Integration'], ['COMPANY', 'About', 'Contact']].map(([heading, ...links]) => <div key={heading}><h3 className="text-xs font-bold tracking-[.08em]">{heading}</h3><div className="mt-4 space-y-3 text-sm opacity-80">{links.map((link) => <a className="block" href="#top" key={link}>{link}</a>)}</div></div>)}</div><div className="flex flex-col gap-5 pt-8 text-sm opacity-60 sm:flex-row sm:items-center sm:justify-between"><p>© 2024 MediMate. All rights reserved.</p><p className="max-w-2xl sm:text-right">MediMate provides AI-assisted health information and does not replace professional medical advice. Always consult a healthcare provider for diagnosis and treatment.</p></div></div></footer></> }

export default function Landing() { return <main className="bg-transparent font-sans text-[#171d1b]"><Navbar /><Hero /><Problem /><Assistant /><Referral /><Journey /><Dashboard /><Connected /><Accessibility /><Footer /></main> }
